# Generated by Django 6.0.6 on 2026-06-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, verbose_name='Mahsulot nomi')),
                ('jami_soni', models.IntegerField(default=0, verbose_name='Jami kelgan soni')),
                ('dokonlarga_berilgani', models.IntegerField(default=0, verbose_name="Do'konlarga berilgani")),
                ('tannarxi', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Olingan narxi (Tannarxi)')),
                ('sotish_narxi', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sotiladigan narxi')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': '1. Mahsulotlar Ombori',
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
